# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "koltes"
locale: "en-US"
email: "koltes.info@gmail.com"
description: " "
#twitter_username: username
#github_username: koltes
minimal_mistakes_skin: default
url: https://koltes.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: ""
repository: koltes/koltes.github.io
teaser: "/assets/images/avatar.png"
logo: "/assets/images/logo_texto.png"
masthead_title: " "
breadcrumbs: true # true, false (default)
search: true


# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.19.1"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
#timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-seo-tag

#author:
#  name   : "koltes"
#  avatar : /assets/images/favicon.png
#  bio    : " "
#  links:
#    - label: "Website"
#      icon: "fas fa-fw fa-link"
#      url: "https://koltes.github.io"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/koltes"
    

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

# Collections
collections:
  touchdesigner:
    output: true
    permalink: /:collection/:path/
  disguise:
    output: true
    permalink: /:collection/:path/
  iluminacion:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/    

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "side"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "side"
  # _touchdesigner
  - scope:
      path: ""
      type: touchdesigner
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "side"
      #sidebar:
      #  nav: "docs"
  # _disguise
  - scope:
      path: ""
      type: disguise
    values:
      layout: single
      author_profile: false
      share: true
      comments: true
      sidebar:
        nav: "side"
  # _iluminacion
  - scope:
      path: ""
      type: iluminacion
    values:
      layout: single
      author_profile: false
      share: true
      comment: true
      sidebar:
        nav: "side"
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
      sidebar:
        nav: "side"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
touchdesigner_archive:
  type: liquid
  path: /touchdesigner/
disguise_archive:
  type: liquid
  path: /disguise/
iluminacion_archive:
  type: liquid
  path: /iluminacion/
portfolio_archive:
  type: liquid
  path: /portfolio/

# Sass/SCSS
#sass:
#  sass_dir: _sass
#  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
